### PR TITLE
sqliteexecute() and sqlitecommit() commands

### PR DESCRIPTION
**Pull request by zarino**
Code mostly taken from the ScraperWiki Classic [scraperwiki.php](https://bitbucket.org/ScraperWiki/scraperwiki-classic/src/6c23fb017064c956c5c565b267f34d4c96fc381a/scraperlibs/php/scraperwiki.php?at=default) module.

Not sure how to test it though!! I can't even get `scraperwiki::save()` to work in the _Code in your browser_ tool.

### CODE REVIEW

**Comment by zarino** [comment]
Okay, got it working.

In my (limited) testing, it appears to work. Although `scraperwiki::sqliteexecute()` and `scraperwiki::sqlitecommit()` don't return the same values as they used to in Classic. I doubt anyone will know or care. And if they do, they can submit a pull request ;-)

Suggest @drj11 merges and deploys this at his earliest convenience.

**Comment by webwithin** [comment]
Hi Zarino.

When I try to use the following in the 'code in your browser' tool
scraperwiki::sqliteexecute("drop table if exists swdata");

I get the error
HP Fatal error:  Call to undefined method scraperwiki::sqliteexecute() in /home/code/scraper on line 7

Is there a file I need to include or should this work?

Thanks.

**Comment by zarino** [comment]
That should "just work". Maybe one of the ScraperWiki guys @drj11 @pwaller @frabcus might have an idea.

**Comment by drj11** [comment]
It's not deployed yet.

**Pull request merged**
